---
name: kotary e2e testing
on: push
jobs:
  kind:
    runs-on: ubuntu-latest
    name: Test Kotary Operator on Kind cluster. Kube version
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
          - 1.21
          - 1.23
          - 1.24
          - 1.26
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Docker Build image
        run: | 
          docker build -t "ci/kotary:${{ matrix.kubernetes }}" .
          docker image ls | grep ci

      - name: Create cluster KinD
        uses: helm/kind-action@v1.5.0
        with:
          config: e2e/KindConfig/kind-cluster-${{ matrix.kubernetes }}.yaml

      - name: testing cluster kinD
        run: | 
              kubectl cluster-info --context kind-chart-testing echo " current-context:" $(kubectl config current-context)
              kubectl get all --all-namespaces
        
      - name: Load docker image into kind cluster
        run: kind load docker-image "ci/kotary:${{ matrix.kubernetes }}" --name chart-testing
          
      - name: Set GOROOT
        run: echo "export GOROOT=/opt/hostedtoolcache/go/1.20/x64" >> $GITHUB_ENV
      
      - name: Deploy CRD
        run: kubectl apply -f artifacts/crd.yml

      - name: Edit kotary deployement
        run: |
          version=${{ matrix.kubernetes }}
          sed -i -E -e "s/cagip\/kotary:v[0-9.]+/ci\/kotary:$version/g" artifacts/deployment.yml -e "s/Always/Never/g" artifacts/deployment.yml;
          cat artifacts/deployment.yml

      - name: run tests
        run: ./e2e/e2e.sh