---
name: kotary e2e testing
on: push
jobs:
  kind:
    runs-on: ubuntu-latest
    name: Test Kotary Operator on Kind cluster. Kube version
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
          - 1.21
          - 1.23
          - 1.24
          - 1.25
          - 1.26
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Export build version
        run: echo "kotary_image=kotary:${{ github.sha }}" >> "$GITHUB_ENV"

      - name: Docker Build image
        run: docker build -t $kotary_image .

      - name: Create cluster KinD
        uses: helm/kind-action@v1.5.0
        with:
          config: e2e/KindConfig/kind-cluster-${{ matrix.kubernetes }}.yaml

      - name: testing cluster kinD
        run: kubectl get pods --all-namespaces

      - name: Load docker image into kind cluster
        run: kind load docker-image "$kotary_image"

      - name: Deploy CRD
        run: kubectl apply -f artifacts/crd.yml

      - name: Edit kotary deployement
        run: |
          sed -i -E -e "s#cagip/kotary:v[0-9.]+#$kotary_image#g" artifacts/deployment.yml -e "s#Always#Never#g" artifacts/deployment.yml;
          cat artifacts/deployment.yml

      - name: run tests
        run: ./e2e/e2e.sh
