---
name: kotary e2e testing
on: push
jobs:
  kind:
    runs-on: ubuntu-latest
    name: create cluster KinD  with (1.21,1.23) Kub version
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
          - 1.21
          - 1.23
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          go-path: ${{ github.workspace }}/go

      - name: Create cluster KinD
        uses: helm/kind-action@v1.5.0
        with:
          config: .github/kind-cluster-${{ matrix.kubernetes }}.yaml
      - name: testing cluster kinD
        run: kubectl cluster-info --context kind-chart-testing echo " current-context:"
          $(kubectl config current-context)
                 
      - name: Setting up kubeconfig ENV for Github Action
        run: echo ::set-env name=KUBE_CONFIG_DATA::$(base64 -w 0 ~/.kube/config)
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          
      - name: Set GOROOT
        run: echo "export GOROOT=/opt/hostedtoolcache/go/1.17.13/x64" >> $GITHUB_ENV