name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

    
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run Tests
        run: make test
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.9
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls, publish coverage results
        uses: coverallsapp/github-action@v2.2.0
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov