
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resourcequotaclaims.ca-gip.github.com
spec:
  group: ca-gip.github.com
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
  names:
    singular: resourcequotaclaim
    plural: resourcequotaclaims
    listKind: ResourceQuotaClaimList
    kind: ResourceQuotaClaim
    shortNames:
      - quotaclaim
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            cpu:
              pattern: '([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
            memory:
              pattern: '([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
        status:
          type: object
          properties:
            phase:
              type: string
            details:
              type: string
  additionalPrinterColumns:
    - name: CPU
      type: string
      description: Desired amount of CPU
      JSONPath: .spec.cpu
    - name: RAM
      type: string
      description: Desired amount of RAM
      JSONPath: .spec.memory
    - name: Status
      type: string
      description: Status of the claim
      JSONPath: .status.phase
    - name: Details
      type: string
      description: Details regarding the status
      JSONPath: .status.details
