
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcequotaclaims.cagip.github.com
spec:
  group: cagip.github.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                cpu:
                  x-kubernetes-int-or-string: true
                  pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
                memory:
                  x-kubernetes-int-or-string: true
                  pattern: '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
            status:
              type: object
              properties:
                phase:
                  type: string
                details:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: CPU
          type: string
          description: Desired amount of CPU
          jsonPath: .spec.cpu
        - name: RAM
          type: string
          description: Desired amount of RAM
          jsonPath: .spec.memory
        - name: Status
          type: string
          description: Status of the claim
          jsonPath: .status.phase
        - name: Details
          type: string
          description: Details regarding the status
          jsonPath: .status.details
  names:
    singular: resourcequotaclaim
    plural: resourcequotaclaims
    listKind: ResourceQuotaClaimList
    kind: ResourceQuotaClaim
    shortNames:
      - quotaclaim
  scope: Namespaced