{
 "title": "Kotary",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_labels, label_name)"
   },
   { "name": "memory_overcommit", "query": "${VAR_MEMORY_OVERCOMMIT}" },
   { "name": "cpu_overcommit", "query": "${VAR_CPU_OVERCOMMIT}" },
   { "name": "memory_max_ns", "query": "${VAR_MEMORY_MAX_NS}" },
   { "name": "cpu_max_ns", "query": "${VAR_CPU_MAX_NS}" }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Overcommit",
   "type": "singlestat",
   "description": "The overcommit ratio for CPU and Memory to allow more resource to be reserved than whats is actually allocatable",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "vector($cpu_overcommit)" }
   ]
  },
  {
   "title": "Max CPU per NS",
   "type": "singlestat",
   "description": "Ratio of the maximum amount of Memory and CPU that can be claimed on a namespace",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "vector($cpu_max_ns)" }
   ]
  },
  {
   "title": "Total CPU Allocatable ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"worker.+\"}) * $cpu_overcommit"
    }
   ]
  },
  {
   "title": "CPU  Reserved",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"hard\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU  Claimable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"worker.+\"}) * $cpu_overcommit - sum(kube_resourcequota{type=\"hard\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Amount Reserved Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"hard\", resource=\"cpu\"}) / sum(kube_node_status_allocatable_cpu_cores{node=~\"worker.+\"})",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(kube_resourcequota{type=\"hard\", resource=\"memory\"}) / sum(kube_node_status_allocatable_memory_bytes{node=~\"worker.+\"}) ",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Memory Overcommit",
   "type": "singlestat",
   "description": "The overcommit ratio for CPU and Memory to allow more resource to be reserved than whats is actually allocatable",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "vector($memory_overcommit)" }
   ]
  },
  {
   "title": "Max Memory per NS",
   "type": "singlestat",
   "description": "Ratio of the maximum amount of Memory and CPU that can be claimed on a namespace",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    { "expr": "vector($memory_max_ns)" }
   ]
  },
  {
   "title": "Memory Allocatable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"worker.+\"}) * $memory_overcommit"
    }
   ]
  },
  {
   "title": "Memory Reserved",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_resourcequota{type=\"hard\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Claimable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"worker.+\"}) * $memory_overcommit - sum(kube_resourcequota{type=\"hard\", resource=\"memory\"})"
    }
   ]
  },
  { "title": "All Namespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Managed Quota",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (namespace) (kube_resourcequota{type=\"used\", resource=\"cpu\"}) / sum by (namespace) (kube_resourcequota{type=\"hard\", resource=\"cpu\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{type=\"used\", resource=\"cpu\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{type=\"hard\", resource=\"cpu\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{type=\"used\", resource=\"memory\"}) / sum by (namespace) (kube_resourcequota{type=\"hard\", resource=\"memory\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{type=\"used\", resource=\"memory\"})"
    },
    {
     "expr": "sum by (namespace) (kube_resourcequota{type=\"hard\", resource=\"memory\"})"
    }
   ]
  },
  { "title": "Namespace Details : $namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Current Memory Quota",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_resourcequota{resource=\"memory\",type=\"hard\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Memory Managment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"POD\",image!=\"\",job=\"kubelet\",namespace=~\"$namespace\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{container!=\"POD\",namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "kube_resourcequota{resource=\"memory\",type=\"hard\",namespace=~\"$namespace\"}",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Memory Expandable Up To",
   "type": "singlestat",
   "description": "The maximum amount of Memory that can be claimed on the namespace",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 25 },
   "format": "bytes",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes{node=~\"worker.+\"}) * $memory_overcommit - sum(kube_resourcequota{type=\"hard\", resource=\"memory\"}) < :node_memory_MemAvailable_bytes:sum * $memory_max_ns or :node_memory_MemAvailable_bytes:sum * $memory_max_ns"
    }
   ]
  },
  {
   "title": "Current CPU Quota",
   "type": "singlestat",
   "description": "The maximum amount of CPU that can be claimed on the namespace",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kube_resourcequota{resource=\"cpu\",type=\"hard\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Managment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_resourcequota{resource=\"cpu\",type=\"hard\",namespace=~\"$namespace\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{container!=\"POD\",namespace=\"$namespace\"}) ",
     "legendFormat": "Request"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{container!=\"POD\",image!=\"\",job=\"kubelet\", namespace=\"$namespace\"}[30s])) * 100\n",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Expandable Up To",
   "type": "singlestat",
   "description": "The maximum amount of CPU that can be claimed on the namespace",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{node=~\"worker.+\"}) * $cpu_overcommit - sum(kube_resourcequota{type=\"hard\", resource=\"cpu\"})  < sum(kube_node_status_allocatable_cpu_cores{node=~\"worker.+\"}) * $cpu_max_ns - sum(kube_resourcequota{type=\"hard\", resource=\"cpu\"}) or sum(machine_cpu_cores{node=~\"worker.*\"}) * $cpu_max_ns "
    }
   ]
  }
 ]
}