---
apiVersion: v1
kind: Service
metadata:
  name:  kotary-svc
  namespace: kube-system
  labels:
    app: kotary
spec:
  ports:
    - name: metrics
      port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: kotary
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kotary
  namespace: kube-system
spec:
  endpoints:
    - interval: 15s
      port: metrics
  selector:
    matchLabels:
      app: kotary